### ISSUE TITLE
pretty-1.1.3.1 fails Haddock phase

### ISSUE THREAD

**Issue by peti** [haskell/pretty#25]
Citing from http://hydra.cryp.to/build/618012/nixlog/2/raw:

    Running Haddock for pretty-1.1.3.1...
    Running hscolour for pretty-1.1.3.1...
    Preprocessing library pretty-1.1.3.1...
    Preprocessing test suite 'test-pretty' for pretty-1.1.3.1...
    Preprocessing library pretty-1.1.3.1...

    src/Text/PrettyPrint/Annotated/HughesPJ.hs:1082:31:
        parse error on input ‘-- ^ this seems wrong, but remember that it's
                                  -- working backwards at this point’

**Comment by osa1** [comment]
This is fixed in #24.
